apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ac-integration-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:uzgidro/GitOps-Repo.git
    targetRevision: main
    path: apps/ac-integration/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
